#+title: Lecture 0

Learning C, Python

C is a low level programming language, performant, control.

Python high level, abstraction, fast development.

Databases, 

HTML Web Development

Frameworks and libraries


What matters is the delta between the you after and before learning.


CS50 Puzzle

Final project,

CS50 fair, exhibition, demo of what you've done.

* Week 0
Computational thinking
- Using scratch to explore computational fundaments.
  
* Week 1
Learning C

- Learning industry standard tool, VS Code, Codespace?
- Explore principles, underneath the hood, RAM.
- Memory, registry, go to, bytes.
  
- Bugs and debugging
  Buggy code, computer encounter mistakes and crashes.

- Algorithms to solve problems, sorting
  What is an algorithm? Translate into code.

- Hash table, array, linked list?
  How to build structures 2 dimensions.
  sorting, how to add code to existing code.

  

* What is compute science?

Computer is the study of information, computational thinking.

How to solve problems, with information.

** What is solving a problem?

*** Input (data)
*** Black box (algorith)
*** Output (representation)

* Unary (base-1)
How we count people and things with fingers
* Binary (base-2)
bit --> 0 || 1, ON || OFF

byte
